name: Go Benchmark (1.17)

on: [push]

jobs:
  benchmark:
    env:
      IS_TEST: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Install Dependencies
        run: go mod download
      - name: Go Benchmark
        run: go test -benchmem -bench=. $(go list ./...)
