name: Go Test (1.14)

on: [push]

jobs:
  test:
    env:
      IS_TEST: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - name: Install Dependencies
        run: go mod download
      - name: Go Test
        run: go test -race $(go list ./...)
